"""empty message

Revision ID: 3b4ec18fa3a8
Revises: a13298656b8d
Create Date: 2016-04-27 23:09:11.587629

"""

# revision identifiers, used by Alembic.
revision = '3b4ec18fa3a8'
down_revision = 'a13298656b8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    ### end Alembic commands ###
