"""empty message

Revision ID: 319ffcce885b
Revises: a13298656b8d
Create Date: 2016-04-27 23:04:14.772952

"""

# revision identifiers, used by Alembic.
revision = '319ffcce885b'
down_revision = 'a13298656b8d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String())
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.String(),
               type_=mysql.INTEGER(display_width=11))
    ### end Alembic commands ###
